// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXmh_ogFAQg-gEmxbiOj6T-ygBUjJM3y8',
    appId: '1:843624484538:web:eb521a9a60e36daae83c83',
    messagingSenderId: '843624484538',
    projectId: 'subtitleproject-bda14',
    authDomain: 'subtitleproject-bda14.firebaseapp.com',
    storageBucket: 'subtitleproject-bda14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA13I1I1OXStChW3st9g3uDHPyJMASwujI',
    appId: '1:843624484538:android:522f246ca49c506ae83c83',
    messagingSenderId: '843624484538',
    projectId: 'subtitleproject-bda14',
    storageBucket: 'subtitleproject-bda14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwNsxdb49iSpiL67oMRTEopOTJBDvGGo',
    appId: '1:843624484538:ios:dc4f08ed8786b289e83c83',
    messagingSenderId: '843624484538',
    projectId: 'subtitleproject-bda14',
    storageBucket: 'subtitleproject-bda14.appspot.com',
    iosClientId: '843624484538-02iagp79k505aflkipgtrdumh2j7ppv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.subtitleGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwNsxdb49iSpiL67oMRTEopOTJBDvGGo',
    appId: '1:843624484538:ios:dc4f08ed8786b289e83c83',
    messagingSenderId: '843624484538',
    projectId: 'subtitleproject-bda14',
    storageBucket: 'subtitleproject-bda14.appspot.com',
    iosClientId: '843624484538-02iagp79k505aflkipgtrdumh2j7ppv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.subtitleGame',
  );
}
